/** @format */
export const SET_INITIALIZED = "[APP]INITIALIZED";
export const SET_VERSION = "[APP]VERSION";
export const SET_ONBOARDED = "[APP]ONBOARDED";
export const SET_SETTINGS = "[APP]SET_SETTINGS";
export const SET_PREFERENCES = "[APP]SET_PREFERENCES";

export const SET_AUTHENTICATED = "[AUTH]SET_AUTHENTICATED";
export const SET_TOKEN = "[AUTH]SET_TOKEN";
export const SET_USER = "[AUTH]SET_USER";

/*
------------------------
DEVIZE ACTIONS
------------------------
*/

export const SET_IDENTITY = "[DEVICE] SET_IDENTITY";
export const SET_OPERATING_SYSTEM = "[DEVICE] SET_OPERATING_SYSTEM";
export const SET_BROWSER = "[DEVICE] SET_BROWSER";
export const SET_SCREEN_SIZE = "[DEVICE] SET_SCREEN_SIZE";
export const SET_WINDOW_SIZE = "[DEVICE] SET_WINDOW_SIZE";
export const SET_LOCATION = "[DEVICE] SET_LOCATION";
/*
------------------------
WEBSOCKETS ACTIONS
------------------------
*/
export const SET_DEFAULT_SOCKET = "[SOCKET] SET_DEFAULT_SOCKET";
export const SET_AUTH_SOCKET = "[SOCKET] SET_AUTH_SOCKET";

/*
------------------------
UI ACTIONS
------------------------
*/
//
// -------LAYOUTS-------
//
// DASHBOARD
export const SET_DASHBOARD_LANGUAGE = "[DASHBOARD] SET_DASHBOARD_LANGUAGE";
export const SET_DASHBOARD_LAYOUT_DIRECTION = "[DASHBOARD] SET_DASHBOARD_LAYOUT_DIRECTION";
export const SET_DASHBOARD_APPBAR_DISPLAYED = "[DASHBOARD] SET_DASHBOARD_APPBAR_DISPLAYED";
export const SET_DASHBOARD_DRAWER_DISPLAYED = "[DASHBOARD] SET_DASHBOARD_DRAWER_DISPLAYED";
export const SET_DASHBOARD_FOOTER_DISPLAYED = "[DASHBOARD] SET_DASHBOARD_FOOTER_DISPLAYED";
export const SET_DASHBOARD_SEARCHBAR_DISPLAYED = "[DASHBOARD] SET_DASHBOARD_SEARCHBAR_DISPLAYED";
export const SET_DASHBOARD_HOMEPAGE_STATE = "[DASHBOARD] SET_DASHBOARD_HOMEPAGE_STATE";
export const SET_DASHBOARD_LIGHTBOX = "[DASHBOARD] SET_DASHBOARD_LIGHTBOX";
// LANDINGPAGE
export const SET_LANDINGPAGE_LANGUAGE =
	"[LANDINGPAGE] SET_LANDINGPAGE_LANGUAGE";
export const SET_LANDINGPAGE_LAYOUT_DIRECTION =
	"[LANDINGPAGE] SET_LANDINGPAGE_LAYOUT_DIRECTION";
export const SET_LANDINGPAGE_NAVBAR_DISPLAYED =
	"[LANDINGPAGE] SET_LANDINGPAGE_NAVBAR_DISPLAYED";
export const SET_LANDINGPAGE_FOOTER_DISPLAYED =
	"[LANDINGPAGE] SET_LANDINGPAGE_FOOTER_DISPLAYED";
export const SET_LANDINGPAGE_LIGHTBOX =
	"[LANDINGPAGE] SET_LANDINGPAGE_LIGHTBOX";

// DIALOG
export const OPEN_DIALOG = "[DIALOG] OPEN";
export const CLOSE_DIALOG = "[DIALOG] CLOSE";
export const OPEN_PROGRESS_DIALOG = "[DIALOG] PROGRESS_OPEN";
export const CLOSE_PROGRESS_DIALOG = "[DIALOG] PROGRESS_CLOSE";

// NAV
export const APPEND_NAV_HISTORY = "APPEND_NAV_HISTORY";
export const CLEAR_NAV_HISTORY = "CLEAR_NAV_HISTORY";
export const SET_NAV_HISTORY_THRESHOLD = "SET_NAV_HISTORY_THRESHOLD";
export const SET_NAV_LOADING = "SET_NAV_LOADING";

//FLASH MESSAGES
export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";

//ECOMMERCE
export const SET_CART = "[ECOMMERCE] SET_CART";
export const ADD_TO_CART = "[ECOMMERCE] ADD_TO_CART";
export const REMOVE_FROM_CART = "[ECOMMERCE] REMOVE_FROM_CART";
export const EMPTY_CART = "[ECOMMERCE] EMPTY_CART";
export const SET_ORDER_PROGRESS = "[ECOMMERCE] SET_ORDER_PROGRESS";
export const SET_ORDER = "[ECOMMERCE] SET_ORDER";
export const SET_CART_NOTE = "[ECOMMERCE] SET_CART_NOTE";
export const SET_CHECKOUT_DATA = "[ECOMMERCE] SET_CHECKOUT_DATA";
export const RESET_ECOMMERCE = "[ECOMMERCE] RESET_ECOMMERCE";

//CACHE
export const SET_DATA_CACHE = "[CACHE] SET_DATA_CACHE";
export const REMOVE_DATA_CACHE = "[CACHE] REMOVE_DATA_CACHE";
export const CLEAR_DATA_CACHE = "[CACHE] CLEAR_DATA_CACHE";
export const SET_RESPONSE_CACHE = "[CACHE] SET_RESPONSE_CACHE";
export const REMOVE_RESPONSE_CACHE = "[CACHE] REMOVE_RESPONSE_CACHE";
export const CLEAR_RESPONSE_CACHE = "[CACHE] CLEAR_RESPONSE_CACHE";
export const SET_BLOB_CACHE = "[CACHE] SET_BLOB_CACHE";
export const REMOVE_BLOB_CACHE = "[CACHE] REMOVE_BLOB_CACHE";
export const CLEAR_BLOB_CACHE = "[CACHE] CLEAR_BLOB_CACHE";
export const CLEAR_CACHE = "[CACHE] CLEAR_CACHE";

//COMMUNICATION CACHE
export const SET_MESSAGING_CACHE = "[COMMUNICATION] SET_MESSAGING_CACHE";
export const REMOVE_MESSAGING_CACHE = "[COMMUNICATION] REMOVE_MESSAGING_CACHE";
export const CLEAR_MESSAGING_CACHE = "[COMMUNICATION] CLEAR_MESSAGING_CACHE";
export const SET_EMAILING_CACHE = "[COMMUNICATION] SET_EMAILING_CACHE";
export const REMOVE_EMAILING_CACHE = "[COMMUNICATION] REMOVE_EMAILING_CACHE";
export const CLEAR_EMAILING_CACHE = "[COMMUNICATION] CLEAR_EMAILING_CACHE";
export const CLEAR_COMMUNICATION_CACHE = "[COMMUNICATION] CLEAR_CACHE";

//API
export const API_CALL_REQUEST = "[API] CALL_REQUEST";
export const API_SET_LOADING = "[API] SET_LOADING";
export const API_ADD_TASK = "[API] ADD_TASK";
export const API_REMOVE_TASK = "[API] REMOVE_TASK";
export const API_CLEAR_TASKS = "[API] CLEAR_TASKS";
export const API_SET_RESPONSE = "[API] SET_RESPONSE";
export const API_SET_COMPLETE = "[API] SET_COMPLETE";
export const API_SET_ERROR = "[API] SET_ERROR";

// CONSENTS
export const SET_CONSENT_VALUE = "[CONSENT] SET_VALUE";
export const SHOW_CONSENT = "[CONSENT] SHOW_CONSENT";


export const CLEAR_APP_STATE = "[APP] CLEAR_STATE";
