# get the base node image
FROM node:alpine as builder

# set the working dir for container
WORKDIR /frontend
RUN npm install -g npm-run-all
# copy the json file first
COPY ./package.json /frontend

# install npm dependencies
RUN npm install

# copy other project files
COPY . .

# build the folder
RUN npm run build:production

# Handle Nginx
FROM nginx
COPY --from=builder /frontend/production /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
