# production environment
FROM nginx:stable-alpine
RUN mkdir -p /usr/share/nginx/html/errors
COPY ./nginx/errors /usr/share/nginx/html/errors
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./production /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]