export const SET_AUTHENTICATED = "[AUTH]SET_AUTHENTICATED";
export const SET_ACCESS_TOKEN = "[AUTH]SET_ACCESS_TOKEN";
export const SET_USER = "[AUTH]SET_USER";

/*
------------------------
DEVIZE ACTIONS
------------------------
*/
export const SET_IDENTITY = "[DEVICE] SET_IDENTITY";
export const SET_OPERATING_SYSTEM = "[DEVICE] SET_OPERATING_SYSTEM";
export const SET_BROWSER = "[DEVICE] SET_BROWSER";
export const SET_SCREEN_SIZE = "[DEVICE] SET_SCREEN_SIZE";
export const SET_WINDOW_SIZE = "[DEVICE] SET_WINDOW_SIZE";


/*
------------------------
WEBSOCKETS ACTIONS
------------------------
*/
export const SET_DEFAULT_SOCKET = "[SOCKET] SET_DEFAULT_SOCKET";
export const SET_AUTH_SOCKET = "[SOCKET] SET_AUTH_SOCKET";

/*
------------------------
UI ACTIONS
------------------------
*/
//
// -------LAYOUTS-------
//
// DASHBOARD
export const SET_DASHBOARD_LANGUAGE = "[DASHBOARD] SET_DASHBOARD_LANGUAGE";
export const SET_DASHBOARD_LAYOUT_DIRECTION = "[DASHBOARD] SET_DASHBOARD_LAYOUT_DIRECTION";
export const SET_DASHBOARD_APPBAR_DISPLAYED = "[DASHBOARD] SET_DASHBOARD_APPBAR_DISPLAYED";
export const SET_DASHBOARD_DRAWER_DISPLAYED = "[DASHBOARD] SET_DASHBOARD_DRAWER_DISPLAYED";
export const SET_DASHBOARD_FOOTER_DISPLAYED = "[DASHBOARD] SET_DASHBOARD_FOOTER_DISPLAYED";
export const SET_DASHBOARD_HOMEPAGE_STATE = "[DASHBOARD] SET_DASHBOARD_HOMEPAGE_STATE";
// LANDINGPAGE
export const SET_LANDINGPAGE_LANGUAGE = "[LANDINGPAGE] SET_LANDINGPAGE_LANGUAGE";
export const SET_LANDINGPAGE_LAYOUT_DIRECTION = "[LANDINGPAGE] SET_LANDINGPAGE_LAYOUT_DIRECTION";
export const SET_LANDINGPAGE_NAVBAR_DISPLAYED = "[LANDINGPAGE] SET_LANDINGPAGE_NAVBAR_DISPLAYED";
export const SET_LANDINGPAGE_FOOTER_DISPLAYED = "[LANDINGPAGE] SET_LANDINGPAGE_FOOTER_DISPLAYED";
export const SET_LANDINGPAGE_ORDERPAGE_STATE = "[LANDINGPAGE] SET_LANDINGPAGE_ORDERPAGE_STATE";


// DIALOG
export const OPEN_DIALOG = "[DIALOG] OPEN";
export const CLOSE_DIALOG = "[DIALOG] CLOSE";
export const OPEN_PROGRESS_DIALOG = "[DIALOG] PROGRESS_OPEN";
export const CLOSE_PROGRESS_DIALOG = "[DIALOG] PROGRESS_CLOSE";


// NAV
export const APPEND_NAV_HISTORY = "APPEND_NAV_HISTORY";
export const CLEAR_NAV_HISTORY = "CLEAR_NAV_HISTORY";
export const SET_NAV_HISTORY_THRESHOLD = "SET_NAV_HISTORY_THRESHOLD";
export const SET_NAV_LOADING = "SET_NAV_LOADING";

//FLASH MESSAGES
export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";



